name: Test
on:
  push:
  pull_request:
  schedule:
    - cron: '0 5 * * *'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install
      run: npm i
    - name: Build
      run: npm run build
    - name: Test
      run: npm test
